import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/extra/navbar";
import { MyProvider } from "../components/context/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
      
        <MyProvider>
        <Navbar/>
          {children}
        </MyProvider>
      </body>
    </html>
  );
}
